/**
 * DISCLAIMER: The documentation on this file was generated by ChatGPT (OpenAI) co-author ChatGPT-5*
 */
package ch.eureka.eurekapp.screens

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Description
import androidx.compose.material.icons.filled.Person
import androidx.compose.material.icons.filled.PersonAdd
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ElevatedButton
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.IconButtonDefaults
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import ch.eureka.eurekapp.model.data.project.Project
import ch.eureka.eurekapp.model.data.project.ProjectSelectionScreenViewModel
import ch.eureka.eurekapp.model.data.project.ProjectStatus
import ch.eureka.eurekapp.model.data.user.User
import ch.eureka.eurekapp.ui.components.IconTextRow
import ch.eureka.eurekapp.ui.designsystem.tokens.EColors.BorderGrayColor
import ch.eureka.eurekapp.ui.designsystem.tokens.EColors.LightingBlue
import ch.eureka.eurekapp.ui.designsystem.tokens.EColors.SuccessGreen
import ch.eureka.eurekapp.ui.designsystem.tokens.EColors.WarningOrange
import ch.eureka.eurekapp.ui.theme.DarkColorScheme
import ch.eureka.eurekapp.ui.theme.LightColorScheme
import ch.eureka.eurekapp.ui.theme.Typography

/** Object holding test tags for UI testing on ProjectSelectionScreen. */
object ProjectSelectionScreenTestTags {
  const val CREATE_PROJECT_BUTTON = "create project button"
  const val INPUT_TOKEN_BUTTON = "input token button"

  fun getNavigateButtonTestTagForButton(projectid: String): String {
    return "Navigate button test tag for $projectid"
  }

  fun getInviteButtonTestTag(projectid: String): String {
    return "Invite button test tag for $projectid"
  }
}

/**
 * Main composable for the Project Selection Screen. Displays a "Create Project" button at the top
 * and a scrollable list of ProjectCards.
 *
 * @param onCreateProjectRequest lambda triggered when the create button is clicked.
 * @param onProjectSelectRequest lambda triggered when a project card's navigate button is clicked.
 * @param projectSelectionScreenViewModel optional ViewModel to fetch project data.
 * @param onGenerateInviteRequest lambda triggered when the user wants to generate an invite
 */
@Composable
fun ProjectSelectionScreen(
    onCreateProjectRequest: () -> Unit = {},
    onInputTokenRequest: () -> Unit = {},
    onProjectSelectRequest: (Project) -> Unit = {},
    onGenerateInviteRequest: (String) -> Unit = {},
    projectSelectionScreenViewModel: ProjectSelectionScreenViewModel = viewModel()
) {
  val currentUser =
      remember { projectSelectionScreenViewModel.getCurrentUser() }.collectAsState(null)

  val projectsList =
      remember { projectSelectionScreenViewModel.getProjectsForUser() }.collectAsState(listOf())

  Column(
      modifier = Modifier.fillMaxSize(),
      horizontalAlignment = Alignment.CenterHorizontally,
      verticalArrangement = Arrangement.Center) {
        Column(
            modifier = Modifier.fillMaxWidth(),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center) {
              CustomElevatedButton(
                  onClick = { onCreateProjectRequest() },
                  text = "+ Create Project",
                  typography = Typography.titleLarge,
                  buttonColor = LightingBlue,
                  testTag = ProjectSelectionScreenTestTags.CREATE_PROJECT_BUTTON)
              CustomElevatedButton(
                  onClick = { onInputTokenRequest() },
                  text = "Input Project Token",
                  typography = Typography.titleLarge,
                  buttonColor = LightingBlue,
                  testTag = ProjectSelectionScreenTestTags.INPUT_TOKEN_BUTTON,
              )
            }
        if (projectsList.value.isEmpty()) {
          Row(
              modifier = Modifier.fillMaxSize(),
              horizontalArrangement = Arrangement.Center,
              verticalAlignment = Alignment.CenterVertically) {
                Text(
                    "No projects yet. Create your first project!",
                    style = Typography.bodyMedium,
                    fontWeight = FontWeight(600))
              }
        } else {
          LazyColumn(
              modifier = Modifier.fillMaxSize(),
              horizontalAlignment = Alignment.CenterHorizontally) {
                items(projectsList.value) { project ->
                  ProjectCard(
                      project,
                      projectSelectionScreenViewModel,
                      onProjectSelectRequest,
                      onGenerateInviteRequest,
                      currentUser.value)
                }
              }
        }
      }
}

/**
 * Custom elevated button composable used across the Project Selection Screen.
 *
 * @param onClick lambda triggered when the button is clicked.
 * @param text the label displayed on the button.
 * @param typography the text style to use for the label.
 * @param buttonColor background color of the button.
 * @param testTag optional test tag for UI testing.
 */
@Composable
private fun CustomElevatedButton(
    onClick: () -> Unit,
    text: String,
    typography: TextStyle,
    buttonColor: Color = LightColorScheme.primary,
    testTag: String
) {
  ElevatedButton(
      modifier = Modifier.padding(vertical = 10.dp, horizontal = 10.dp).testTag(testTag),
      onClick = onClick,
      colors = ButtonDefaults.elevatedButtonColors(containerColor = buttonColor),
      elevation = ButtonDefaults.buttonElevation(defaultElevation = 8.dp),
  ) {
    Text(text, style = typography, color = LightColorScheme.surface, textAlign = TextAlign.Center)
  }
}

/**
 * Custom icon button composable used across the Project Selection Screen.
 *
 * @param onClick lambda triggered when the button is clicked.
 * @param buttonColor background color of the button.
 * @param testTag optional test tag for UI testing.
 */
@Composable
private fun CustomIconButton(
    onClick: () -> Unit,
    buttonColor: Color = LightColorScheme.primary,
    testTag: String
) {
  IconButton(
      modifier = Modifier.padding(vertical = 10.dp, horizontal = 10.dp).testTag(testTag),
      onClick = onClick,
      colors = IconButtonDefaults.iconButtonColors(containerColor = buttonColor),
  ) {
    Icon(
        modifier = Modifier.size(20.dp),
        imageVector = Icons.Default.PersonAdd,
        contentDescription = null,
        tint = LightColorScheme.surface)
  }
}

/**
 * Composable representing a single project card. Displays project name, description, users, status,
 * and a navigate button.
 *
 * @param project the Project object to display.
 * @param projectSelectionScreenViewModel ViewModel used to fetch users for the project.
 * @param onProjectSelectRequest lambda triggered when the navigate button is clicked.
 * @param onGenerateInviteRequest lambda triggered when the user requests to generate an invite
 * @param currentUser the user who using the app
 */
@Composable
private fun ProjectCard(
    project: Project,
    projectSelectionScreenViewModel: ProjectSelectionScreenViewModel,
    onProjectSelectRequest: (Project) -> Unit,
    onGenerateInviteRequest: (String) -> Unit,
    currentUser: User?
) {
  Card(
      modifier = Modifier.fillMaxWidth(0.9f).height(220.dp).padding(vertical = 10.dp),
      shape = RoundedCornerShape(16.dp),
      elevation = CardDefaults.cardElevation(defaultElevation = 8.dp),
      border = BorderStroke(1.dp, BorderGrayColor)) {
        Column(
            modifier = Modifier.fillMaxSize(),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Top) {
              // Show name
              Row(
                  modifier = Modifier.padding(vertical = 10.dp),
                  horizontalArrangement = Arrangement.Center) {
                    Text(
                        project.name,
                        style = Typography.titleLarge,
                        textAlign = TextAlign.Center,
                        fontWeight = FontWeight(600))
                  }

              val projectUsers =
                  projectSelectionScreenViewModel
                      .getProjectUsersInformation(project.projectId)
                      .collectAsState(listOf())

              // Description users and status
              Row(
                  modifier = Modifier.fillMaxSize(),
                  horizontalArrangement = Arrangement.Center,
              ) {
                Column(
                    modifier = Modifier.weight(1f),
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.Top,
                ) {
                  Row(modifier = Modifier.weight(2f)) {
                    IconTextRow(
                        text = project.description,
                        iconVector = Icons.Default.Description,
                        iconColor = WarningOrange)
                  }
                  Row(modifier = Modifier.weight(1f), horizontalArrangement = Arrangement.Center) {
                    CustomElevatedButton(
                        onClick = { onProjectSelectRequest(project) },
                        text = "Navigate",
                        typography = Typography.labelSmall,
                        testTag =
                            ProjectSelectionScreenTestTags.getNavigateButtonTestTagForButton(
                                project.projectId))
                    if (currentUser?.uid.equals(project.createdBy)) {
                      CustomIconButton(
                          onClick = { onGenerateInviteRequest(project.projectId) },
                          testTag =
                              ProjectSelectionScreenTestTags.getInviteButtonTestTag(
                                  project.projectId))
                    }
                  }
                }
                Column(modifier = Modifier.weight(1f).fillMaxHeight()) {
                  Row(
                      modifier = Modifier.weight(2f).fillMaxWidth(),
                      horizontalArrangement = Arrangement.Center,
                      verticalAlignment = Alignment.CenterVertically) {
                        LazyColumn(
                            modifier = Modifier.fillMaxSize(),
                            horizontalAlignment = Alignment.CenterHorizontally) {
                              items(projectUsers.value) { user ->
                                IconTextRow(
                                    text = user.displayName,
                                    iconVector = Icons.Default.Person,
                                    iconColor = DarkColorScheme.background)
                              }
                            }
                      }
                  Row(
                      modifier = Modifier.weight(1f).fillMaxWidth(),
                      horizontalArrangement = Arrangement.Center,
                      verticalAlignment = Alignment.CenterVertically) {
                        ProjectStatusDisplay(project.status)
                      }
                }
              }
            }
      }
}

private val colorMap =
    mapOf(
        ProjectStatus.OPEN to SuccessGreen,
        ProjectStatus.IN_PROGRESS to LightColorScheme.tertiary,
        ProjectStatus.ARCHIVED to WarningOrange,
        ProjectStatus.COMPLETED to LightColorScheme.onSurfaceVariant)
/**
 * Displays the status of a project in a colored surface with rounded corners.
 *
 * @param projectStatus the status of the project.
 */
@Composable
fun ProjectStatusDisplay(projectStatus: ProjectStatus) {
  Surface(
      color = colorMap.getOrDefault(projectStatus, LightColorScheme.onSurfaceVariant),
      modifier = Modifier.height(30.dp).width(130.dp),
      shape = RoundedCornerShape(16.dp),
      tonalElevation = 8.dp,
  ) {
    Row(
        modifier = Modifier.fillMaxSize(),
        horizontalArrangement = Arrangement.Center,
        verticalAlignment = Alignment.CenterVertically) {
          Text(projectStatus.name, style = Typography.labelMedium, color = LightColorScheme.surface)
        }
  }
}
