package ch.eureka.eurekapp.ui.meeting

import ch.eureka.eurekapp.model.data.map.Location
import ch.eureka.eurekapp.model.data.meeting.Meeting
import ch.eureka.eurekapp.model.data.meeting.MeetingDateTimeVotes
import ch.eureka.eurekapp.model.data.meeting.MeetingFormat
import ch.eureka.eurekapp.model.data.meeting.MeetingFormatVote
import ch.eureka.eurekapp.model.data.meeting.MeetingStatus
import ch.eureka.eurekapp.model.data.meeting.TimeSlot
import com.google.firebase.Timestamp
import java.util.Calendar

/**
 * Object providing multiple different meetings.
 *
 * Note: this code was generated by Gemini.
 */
object MeetingProvider {
  fun createTimestamp(year: Int, month: Int, day: Int, hour: Int, minute: Int): Timestamp {
    val calendar = Calendar.getInstance()
    calendar.set(year, month - 1, day, hour, minute, 0)
    return Timestamp(calendar.time)
  }

  val userIds = listOf("user_anna", "user_ben", "user_charlie", "user_diana", "user_ethan")
  val projectIds = listOf("proj_apollo", "proj_bravo", "proj_charon")
  val taskIds = listOf("task_ui_refresh", "task_db_migration", "task_api_docs")

  val lausanneOffice = Location(latitude = 46.5197, longitude = 6.6323, name = "Lausanne Office")
  val genevaClientHQ = Location(latitude = 46.2044, longitude = 6.1432, name = "Geneva Client HQ")
  val zurichHub = Location(latitude = 47.3769, longitude = 8.5417, name = "Zurich Innovation Hub")

  val sampleMeetings =
      listOf(
          Meeting(
              meetingID = "meet_vote_01",
              projectId = projectIds[0],
              taskId = taskIds[0],
              title = "Apollo UI Refresh Kick-off",
              datetime = null,
              location = null,
              status = MeetingStatus.SCHEDULED,
              format = null,
              link = null,
              ended = false,
              createdBy = userIds[0],
              participantIds = listOf(userIds[0], userIds[1], userIds[2]),
              canVote = true,
              timeSlot =
                  TimeSlot(
                      startTime = createTimestamp(2025, 10, 20, 9, 0), // Next Monday 9 AM
                      endTime = createTimestamp(2025, 10, 20, 17, 0) // Next Monday 5 PM
                      ),
              dateTimeVotes =
                  listOf(
                      MeetingDateTimeVotes(
                          userIds[0], listOf(createTimestamp(2025, 10, 20, 10, 0))),
                      MeetingDateTimeVotes(
                          userIds[1],
                          listOf(
                              createTimestamp(2025, 10, 20, 11, 0),
                              createTimestamp(2025, 10, 20, 14, 0))),
                      MeetingDateTimeVotes(
                          userIds[2], listOf(createTimestamp(2025, 10, 20, 10, 0)))),
              formatVotes =
                  listOf(
                      MeetingFormatVote(userIds[0], MeetingFormat.VIRTUAL),
                      MeetingFormatVote(userIds[1], MeetingFormat.IN_PERSON),
                      MeetingFormatVote(userIds[2], MeetingFormat.VIRTUAL))),
          Meeting(
              meetingID = "meet_scheduled_virtual_02",
              projectId = projectIds[1],
              title = "Bravo Project Weekly Sync",
              datetime = createTimestamp(2025, 10, 17, 15, 0), // This Friday 3 PM
              location = null,
              status = MeetingStatus.SCHEDULED,
              format = MeetingFormat.VIRTUAL,
              link = "https://meet.google.com/abc-defg-hij",
              ended = false,
              createdBy = userIds[1],
              participantIds = listOf(userIds[1], userIds[3], userIds[4]),
              canVote = false),
          Meeting(
              meetingID = "meet_scheduled_inperson_03",
              projectId = projectIds[0],
              taskId = taskIds[1],
              title = "Database Migration Strategy",
              datetime = createTimestamp(2025, 10, 22, 10, 30), // Next Wednesday 10:30 AM
              location = lausanneOffice,
              status = MeetingStatus.SCHEDULED,
              format = MeetingFormat.IN_PERSON,
              link = null,
              ended = false,
              createdBy = userIds[2],
              participantIds = listOf(userIds[0], userIds[2], userIds[4]),
              canVote = false),
          Meeting(
              meetingID = "meet_completed_inperson_04",
              projectId = projectIds[2],
              title = "Q4 Marketing Brainstorm",
              datetime = createTimestamp(2025, 10, 13, 14, 0), // Last Monday 2 PM
              location = zurichHub,
              status = MeetingStatus.COMPLETED,
              format = MeetingFormat.IN_PERSON,
              attachmentUrls = listOf("https://storage.example.com/notes_q4_marketing.pdf"),
              ended = true,
              createdBy = userIds[3],
              participantIds = listOf(userIds[1], userIds[3]),
              canVote = false),
          Meeting(
              meetingID = "meet_completed_virtual_05",
              projectId = projectIds[1],
              taskId = taskIds[2],
              title = "API Documentation Final Review",
              datetime = createTimestamp(2025, 10, 10, 11, 0), // Last Friday 11 AM
              status = MeetingStatus.COMPLETED,
              format = MeetingFormat.VIRTUAL,
              link = "https://meet.google.com/klm-nopq-rst",
              attachmentUrls =
                  listOf(
                      "https://storage.example.com/api_docs_recording.mp4",
                      "https://storage.example.com/meeting_chat_log.txt"),
              ended = true,
              createdBy = userIds[4],
              participantIds = userIds, // All users participated
              canVote = false),
          Meeting(
              meetingID = "meet_inprogress_06",
              projectId = projectIds[0],
              title = "Live Demo & Feedback Session",
              datetime = createTimestamp(2025, 10, 15, 17, 0), // Today 5 PM
              status = MeetingStatus.IN_PROGRESS,
              format = MeetingFormat.VIRTUAL,
              link = "https://zoom.us/j/1234567890",
              ended = false,
              createdBy = userIds[0],
              participantIds = listOf(userIds[0], userIds[1], userIds[4]),
              canVote = false),
          Meeting(
              meetingID = "meet_cancelled_07",
              projectId = projectIds[2],
              title = "Client On-site Visit",
              datetime = createTimestamp(2025, 10, 24, 9, 0),
              location = genevaClientHQ,
              status = MeetingStatus.CANCELLED,
              format = MeetingFormat.IN_PERSON,
              ended = false,
              createdBy = userIds[3],
              participantIds = listOf(userIds[0], userIds[3]),
              canVote = false),
          Meeting(
              meetingID = "meet_projectwide_08",
              projectId = projectIds[1],
              taskId = null,
              title = "Bravo Project All-Hands",
              datetime = createTimestamp(2025, 11, 3, 16, 0),
              status = MeetingStatus.SCHEDULED,
              format = MeetingFormat.VIRTUAL,
              link = "https://teams.microsoft.com/...",
              ended = false,
              createdBy = userIds[1],
              participantIds = userIds,
              canVote = false),
          Meeting(
              meetingID = "meet_minimal_09",
              projectId = projectIds[0],
              title = "Quick Check-in",
              datetime = createTimestamp(2025, 10, 16, 9, 15),
              status = MeetingStatus.SCHEDULED,
              createdBy = userIds[0],
              participantIds = listOf(userIds[0], userIds[2])),
          Meeting(
              meetingID = "meet_completed_no_attachments_10",
              projectId = projectIds[2],
              title = "Budget Preliminary Discussion",
              datetime = createTimestamp(2025, 9, 30, 13, 0),
              location = lausanneOffice,
              status = MeetingStatus.COMPLETED,
              format = MeetingFormat.IN_PERSON,
              ended = true,
              createdBy = userIds[3],
              participantIds = listOf(userIds[3], userIds[4]),
              canVote = false),
          Meeting(
              meetingID = "meet_vote_complex_11",
              projectId = projectIds[1],
              title = "Service Architecture Planning",
              datetime = null,
              status = MeetingStatus.SCHEDULED,
              format = null,
              ended = false,
              createdBy = userIds[4],
              participantIds = userIds,
              canVote = true,
              timeSlot =
                  TimeSlot(
                      startTime = createTimestamp(2025, 10, 27, 9, 0),
                      endTime = createTimestamp(2025, 10, 28, 17, 0)),
              dateTimeVotes =
                  listOf(
                      MeetingDateTimeVotes(
                          userIds[0], listOf(createTimestamp(2025, 10, 27, 10, 0))),
                      MeetingDateTimeVotes(
                          userIds[1], listOf(createTimestamp(2025, 10, 28, 14, 0))),
                      MeetingDateTimeVotes(
                          userIds[2],
                          listOf(
                              createTimestamp(2025, 10, 27, 10, 0),
                              createTimestamp(2025, 10, 28, 11, 0))),
                      MeetingDateTimeVotes(
                          userIds[3], listOf(createTimestamp(2025, 10, 28, 14, 0))),
                      MeetingDateTimeVotes(
                          userIds[4], listOf(createTimestamp(2025, 10, 27, 13, 0)))),
              formatVotes =
                  listOf(
                      MeetingFormatVote(userIds[0], MeetingFormat.IN_PERSON),
                      MeetingFormatVote(userIds[1], MeetingFormat.VIRTUAL),
                      MeetingFormatVote(userIds[2], MeetingFormat.VIRTUAL),
                      MeetingFormatVote(userIds[3], MeetingFormat.IN_PERSON),
                      MeetingFormatVote(userIds[4], MeetingFormat.IN_PERSON))),
          Meeting(
              meetingID = "meet_future_12",
              projectId = projectIds[0],
              title = "2026 Project Apollo Roadmap",
              datetime = createTimestamp(2025, 12, 15, 11, 0),
              status = MeetingStatus.SCHEDULED,
              format = MeetingFormat.IN_PERSON,
              location = genevaClientHQ,
              createdBy = userIds[0],
              participantIds = listOf(userIds[0], userIds[1], userIds[3]),
              canVote = false),
          Meeting(
              meetingID = "meet_backtoback_13",
              projectId = projectIds[1],
              title = "Bravo Project Weekly Sync (Part 2)",
              datetime = createTimestamp(2025, 10, 17, 16, 0), // Right after meeting #2
              status = MeetingStatus.SCHEDULED,
              format = MeetingFormat.VIRTUAL,
              link = "https://meet.google.com/abc-defg-hij",
              createdBy = userIds[1],
              participantIds = listOf(userIds[1], userIds[3], userIds[4]),
              canVote = false),
          Meeting(
              meetingID = "meet_decided_from_vote_14",
              projectId = projectIds[2],
              title = "Social Media Campaign Launch",
              datetime = createTimestamp(2025, 10, 1, 10, 0),
              status = MeetingStatus.COMPLETED,
              format = MeetingFormat.VIRTUAL,
              link = "https://meet.google.com/uvw-xyza-bcd",
              attachmentUrls = listOf("https://storage.example.com/launch_summary.docx"),
              ended = true,
              createdBy = userIds[2],
              participantIds = listOf(userIds[2], userIds[3]),
              canVote = false,
              dateTimeVotes =
                  listOf(
                      MeetingDateTimeVotes(userIds[2], listOf(createTimestamp(2025, 10, 1, 10, 0))),
                      MeetingDateTimeVotes(
                          userIds[3],
                          listOf(
                              createTimestamp(2025, 10, 1, 10, 0),
                              createTimestamp(2025, 10, 1, 14, 0)))),
              formatVotes =
                  listOf(
                      MeetingFormatVote(userIds[2], MeetingFormat.VIRTUAL),
                      MeetingFormatVote(userIds[3], MeetingFormat.VIRTUAL))),
          Meeting(
              meetingID = "meet_inprogress_inperson_15",
              projectId = projectIds[0],
              title = "Urgent Hotfix Discussion",
              datetime = createTimestamp(2025, 10, 15, 17, 30), // Today 5:30 PM
              location = lausanneOffice,
              status = MeetingStatus.IN_PROGRESS,
              format = MeetingFormat.IN_PERSON,
              ended = false,
              createdBy = userIds[0],
              participantIds = listOf(userIds[0], userIds[4]),
              canVote = false))
}
