package ch.eureka.eurekapp.model.audio

import android.content.Context
import android.net.Uri
import kotlinx.coroutines.flow.Flow
/**
 * Interface defining operations for managing audio recordings.
 *
 * Implementations of this interface are responsible for creating, controlling, and
 * deleting audio recordings. All operations return a [Result] to indicate success or failure.
 *
 * Note: Documentation for this interface and its methods has been AI-generated by ChatGPT.
 */
interface AudioRecordingRepository {

    /**
     * Creates a new audio recording file with the given [fileName] and starts recording.
     *
     * @param fileName The name of the file to create for the recording.
     * @return A [Result] wrapping a [Uri] pointing to the newly created recording file
     *         on success, or an exception describing the failure.
     *
     * Note: This documentation has been AI-generated.
     */
    fun createRecording(fileName: String): Result<Uri>

    /**
     * Clears the current recording without deleting the file.
     *
     * This may be used to reset the recording state and prepare for a new recording.
     *
     * @return A [Result] indicating success or failure of the operation.
     *
     * Note: This documentation has been AI-generated.
     */
    fun clearRecording(): Result<Unit>

    /**
     * Pauses the current audio recording.
     *
     * @return A [Result] indicating success or failure of the operation.
     *
     * Note: This documentation has been AI-generated.
     */
    fun pauseRecording(): Result<Unit>

    /**
     * Resumes a previously paused recording.
     *
     * If the recording is not paused, this may return a failure result.
     *
     * @return A [Result] indicating success or failure of the operation.
     *
     * Note: This documentation has been AI-generated.
     */
    fun resumeRecording(): Result<Unit>

    /**
     * Deletes the current recording file from storage.
     *
     * This operation is irreversible. After deletion, the recording file is no longer available.
     *
     * @return A [Result] indicating success or failure of the deletion operation.
     *
     * Note: This documentation has been AI-generated.
     */
    fun deleteRecording(): Result<Unit>
}