/*
 * This file was co-authored by Claude Code and Gemini.
 */
package ch.eureka.eurekapp.model.data.activity

import kotlinx.coroutines.flow.Flow

/**
 * Repository interface for activity tracking.
 *
 * This repository manages the lifecycle of [Activity] entities. It provides a simplified interface
 * to fetch a unified feed of activities relevant to a specific user, as well as methods to create
 * and delete activities.
 */
interface ActivityRepository {

  /**
   * Fetches all activities that the specific user is allowed to see.
   *
   * This method determines the user's project memberships and retrieves a combined feed of
   * activities from those projects. It also includes activities from global or test contexts (like
   * 'test-project-id') where applicable.
   *
   * @param userId The unique identifier of the user requesting the activities.
   * @return A [Flow] emitting the list of [Activity] objects sorted by timestamp (descending).
   */
  fun getActivities(userId: String): Flow<List<Activity>>

  /**
   * Creates a new activity entry in the database.
   *
   * @param activity The [Activity] object to be created. The `activityId` field in this object is
   *   ignored as a new ID will be generated by the database.
   * @return A [Result] containing the generated activity ID on success, or an exception on failure.
   */
  suspend fun createActivity(activity: Activity): Result<String>

  /**
   * Deletes an activity entry by its ID.
   *
   * @param activityId The unique identifier of the activity to delete.
   * @return A [Result] containing [Unit] on success, or an exception on failure.
   */
  suspend fun deleteActivity(activityId: String): Result<Unit>
}
