/**
 * DISCLAIMER: The documentation on this file was generated by ChatGPT (OpenAI) co-author ChatGPT-5*
 */
package ch.eureka.eurekapp.model.notifications

/**
 * Enum class representing different types of notifications in the application.
 *
 * Each notification type has a [displayString] that can be shown in the notification.
 *
 * @property displayString A user-friendly name for the notification type.
 */
enum class NotificationType(val displayString: String) {
    GENERAL_NOTIFICATION("General"),
    MEETING_NOTIFICATION("Meetings"),
    MESSAGE_NOTIFICATION("Message")
}