/**
 * DISCLAIMER: The documentation on this file was generated by ChatGPT (OpenAI) co-author ChatGPT-5*
 */
package ch.eureka.eurekapp.model.data.project

import androidx.lifecycle.ViewModel
import ch.eureka.eurekapp.model.data.FirestoreRepositoriesProvider
import ch.eureka.eurekapp.model.data.user.User
import ch.eureka.eurekapp.model.data.user.UserRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.flatMapLatest

/**
 * ViewModel for managing project selection screen data. Provides flows of projects for the current
 * user and user details for each project.
 *
 * @param projectsRepository Repository to fetch projects (default:
 *   FirestoreRepositoriesProvider.projectRepository)
 * @param usersRepository Repository to fetch user information (default:
 *   FirestoreRepositoriesProvider.userRepository)
 */
class ProjectSelectionScreenViewModel(
    private val projectsRepository: ProjectRepository =
        FirestoreRepositoriesProvider.projectRepository,
    private val usersRepository: UserRepository = FirestoreRepositoriesProvider.userRepository
) : ViewModel() {

  /**
   * Returns a Flow of the list of projects for the currently logged-in user.
   *
   * @return Flow emitting lists of Project objects.
   */
  fun getProjectsForUser(): Flow<List<Project>> {
    return projectsRepository.getProjectsForCurrentUser(skipCache = false)
  }

  /**
   * Returns a Flow of the list of users associated with a given project. Combines individual user
   * flows into a single flow that emits the list of non-null users.
   *
   * @param projectId The ID of the project for which to retrieve user information.
   * @return Flow emitting lists of User objects for the project.
   */
  fun getProjectUsersInformation(projectId: String): Flow<List<User>> {
    return projectsRepository.getMembers(projectId).flatMapLatest { members ->
      val usersFlow =
          members.map { member -> usersRepository.getUserById(member.userId).catch { emit(null) } }
      combine(usersFlow) { flow -> flow.filterNotNull().toList() }
    }
  }

    fun getCurrentUser(): Flow<User?>{
        return usersRepository.getCurrentUser()
    }
}
