package ch.eureka.eurekapp.model.data.project

import androidx.lifecycle.ViewModel
import ch.eureka.eurekapp.model.data.FirestoreRepositoriesProvider
import ch.eureka.eurekapp.model.data.user.User
import ch.eureka.eurekapp.model.data.user.UserRepository
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.flatMapLatest
import kotlinx.coroutines.flow.map

/**
 * ViewModel for managing project selection screen data.
 * Provides flows of projects for the current user and user details for each project.
 *
 * @param projectsRepository Repository to fetch projects (default: FirestoreRepositoriesProvider.projectRepository)
 * @param usersRepository Repository to fetch user information (default: FirestoreRepositoriesProvider.userRepository)
 *
 * DISCLAIMER: This documentation was generated by ChatGPT (OpenAI) and may require verification.
 */
class ProjectSelectionScreenViewModel(
    private val projectsRepository: ProjectRepository = FirestoreRepositoriesProvider.projectRepository,
    private val usersRepository: UserRepository = FirestoreRepositoriesProvider.userRepository
): ViewModel() {

    /**
     * Returns a Flow of the list of projects for the currently logged-in user.
     *
     * @return Flow emitting lists of Project objects.
     *
     * DISCLAIMER: This documentation was generated by ChatGPT (OpenAI) and may require verification.
     */
    fun getProjectsForUser(): Flow<List<Project>> {
        return projectsRepository.getProjectsForCurrentUser(skipCache = false)
    }

    /**
     * Returns a Flow of the list of users associated with a given project.
     * Combines individual user flows into a single flow that emits the list of non-null users.
     *
     * @param projectId The ID of the project for which to retrieve user information.
     * @return Flow emitting lists of User objects for the project.
     *
     * DISCLAIMER: This documentation was generated by ChatGPT (OpenAI) and may require verification.
     */
    fun getProjectUsersInformation(projectId: String): Flow<List<User>>{
        return projectsRepository.getMembers(projectId).flatMapLatest{ members ->
            val usersFlow = members.map {member -> usersRepository
                .getUserById(member.userId) }
            combine(usersFlow){ flow ->
                flow.filterNotNull().toList()
            }
        }
    }

}