name: "Telegram: sendMessage"
description: "Send a text message to Telegram (HTML/MarkdownV2), optional thread/topic"

inputs:
  text:
    description: "Message text"
    required: true
  parse_mode:
    description: "HTML or MarkdownV2"
    default: "HTML"
    required: false
  bot_token:
    description: "Telegram bot token (pass from workflow with secrets.TELEGRAM_BOT_TOKEN)"
    required: true
  chat_id:
    description: "Target chat id (-100...) or @channelusername (pass from workflow with secrets.TELEGRAM_CHAT_ID)"
    required: true
  thread_id:
    description: "Forum topic id (message_thread_id)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Ensure jq
      shell: bash
      run: |
        if ! command -v jq >/dev/null 2>&1; then
          sudo apt-get update -y && sudo apt-get install -y jq
        fi

    - name: Send to Telegram
      shell: bash
      env:
        TOKEN:      ${{ inputs.bot_token }}
        CHAT_ID:    ${{ inputs.chat_id }}
        TEXT:       ${{ inputs.text }}
        PARSE_MODE: ${{ inputs.parse_mode }}
        THREAD_ID:  ${{ inputs.thread_id }}
      run: |
        set -euo pipefail
        
        PAYLOAD=$(jq -n \
          --arg chat_id "$CHAT_ID" \
          --arg text "$TEXT" \
          --arg parse_mode "$PARSE_MODE" \
          --arg thread_id "${THREAD_ID:-}" \
          '{chat_id:$chat_id, text:$text, parse_mode:$parse_mode}
           + ( if ($thread_id|length) > 0
               then { message_thread_id: ( (($thread_id|tonumber?) // $thread_id) ) }
               else {}
               end )')

        RESP=$(curl -sS "https://api.telegram.org/bot${TOKEN}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD")

        echo "Telegram response: $RESP"
        echo "$RESP" | jq -e '.ok == true' >/dev/null || {
          DESC=$(echo "$RESP" | jq -r '.description // "Unknown error"')
          echo "::error::Telegram API error: $DESC"
          exit 1
        }