name: Telegram — Push Notification
on:
  push: # to any branch
    branches:
      - '**'

jobs:
  notify:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    continue-on-error: true
    steps:
    - name: Checkout repo (required for local actions and scripts)
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Send Telegram notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_THREAD_ID: ${{ vars.TELEGRAM_PUSH_THREAD_ID }}
        EVENT_TYPE: push
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_ACTOR: ${{ github.actor }}
        PUSH_BRANCH: ${{ github.ref_name }}
        PUSH_COMMITS: ${{ toJson(github.event.commits) }}
      run: python3 .github/scripts/telegram_notify.py
