name: Telegram — Push Notification
on:
  push: # to any branch
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout repo (required for local actions and scripts)
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Extract Firestore Rules
      if: github.ref_name == 'feature/project-selection-task-creation'
      run: |
        mkdir -p firebase/firestore firebase/storage
        echo "${{ secrets.FIRESTORE_RULES }}" | base64 -d > firebase/firestore/firestore.rules
        echo "${{ secrets.STORAGE_RULES }}" | base64 -d > firebase/storage/storage.rules
        echo "✅ Rules files created!"

    - name: Send Telegram notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_THREAD_ID: ${{ vars.TELEGRAM_PUSH_THREAD_ID }}
        EVENT_TYPE: push
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_ACTOR: ${{ github.actor }}
        PUSH_BRANCH: ${{ github.ref_name }}
        PUSH_COMMITS: ${{ toJson(github.event.commits) }}
      run: python3 .github/scripts/telegram_notify.py
