name: Get Secrets (TEMPORARY - DELETE AFTER USE)

on:
  workflow_dispatch:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get Firestore Rules
        run: |
          echo "Creating directory..."
          mkdir -p firebase/firestore
          
          echo "FIRESTORE_RULES content (base64):"
          echo "${{ secrets.FIRESTORE_RULES }}"
          
          echo "${{ secrets.FIRESTORE_RULES }}" | base64 -d > firebase/firestore/firestore.rules
          
          echo "Rules file created at firebase/firestore/firestore.rules"
          cat firebase/firestore/firestore.rules
      
      - name: Get Storage Rules
        run: |
          echo "Creating directory..."
          mkdir -p firebase/storage
          
          echo "STORAGE_RULES content (base64):"
          echo "${{ secrets.STORAGE_RULES }}"
          
          echo "${{ secrets.STORAGE_RULES }}" | base64 -d > firebase/storage/storage.rules
          
          echo "Rules file created at firebase/storage/storage.rules"
          cat firebase/storage/storage.rules
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firebase-rules
          path: |
            firebase/firestore/firestore.rules
            firebase/storage/storage.rules

